# Generated by Django 4.1.3 on 2022-12-07 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppLibros', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comic',
            new_name='Comics',
        ),
        migrations.RenameModel(
            old_name='Manga',
            new_name='Mangas',
        ),
    ]
